# Generated by Django 6.0.4 on 2026-04-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='featured_title',
        ),
        migrations.RemoveField(
            model_name='author',
            name='label',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
    ]
