# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: orders_db
        ports:
        - containerPort: 5432

---
# Node.js App Service
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: order-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
# Node.js App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: order-app:local
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: orders_db
        ports:
        - containerPort: 3000